GET http://localhost:3001/api/blogs


###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
	"title": "lol",
	"author": "Batya",
	"url": "http://localhost:3001/api/blogs",
	"likes": 20
}